# Screen
SCREEN_WIDTH = 2560
SCREEN_HEIGHT = 1600
SCREEN_TITLE = "Metroidvania"

# Scaling
PLAYER_SCALING = 0.3
TILE_SCALING = 1
SPRITE_PIXEL_SIZE = 128
GRID_PIXEL_SIZE = SPRITE_PIXEL_SIZE * TILE_SCALING

# Physics
GRAVITY = 0.7
PLAYER_MOVEMENT_SPEED = 5
PLAYER_JUMP_SPEED = 20

# Player
PLAYER_START_X = 64
PLAYER_START_Y = 225
PLAYER_MAX_HEALTH = 150

# Enemy
ENEMY_MOVEMENT_SPEED = 0.5
ENEMY_JUMP_SPEED = 5
ENEMY_MAX_HEALTH = 100
ENEMY_SCALING = 0.2

# Viewport margins
VIEWPORT_MARGIN = 200